services:
  nginx1:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./serveur1:/var/www/html
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    networks:
      - app-network

  nginx2:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./serveur2:/var/www/html
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    networks:
      - app-network

  php1:
    build:
      context: ./docker/php
    volumes:
      - ./serveur1:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - app-network

  php2:
    build:
      context: ./docker/php
    volumes:
      - ./serveur2:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # Port SMTP
      - "8025:8025"  # Interface Web
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  minio_data:
